# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Petro Salema &bull; Designer &middot; Programmer &middot; Speaker
email: contact@petrosalema.com
description: > # this means to ignore newlines until "baseurl:"
  My mission is to bring the promises of the future into the present through
  technology, design and truth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petrosalema.com" # the base hostname & protocol for your site
twitter_username: petrosalema
github_username:  petrosalema
exclude: [.git, .gitignore]

# Build settings
markdown: kramdown


# My book shelf

# Murphy Brown
# The Cry of The Soul
# Counterfeit Gods
# Book me to speak at your conference
# For people who want to make a difference
# step through still as you hover or draf over image
#
# My is Petro, and I work with people who want to make a difference.
# My mission is to...
#
#
# http://www.elliotmidson.com/
# http://www.clementbrichon.com/work/takeit-website/
# http://diegoaguilar.com/
# http://henrikandsofia.com/
#
#
# https://jekyllrb.com/docs/variables/
# https://jekyllrb.com/docs/frontmatter/
# https://jekyllrb.com/docs/structure/
