# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Petro Salema &bull; Designer &middot; Programmer &middot; Speaker
email: contact@petrosalema.com
description: > # this means to ignore newlines until "baseurl:"
  My mission is to bring the promises of the future into the present through
  technology, design and truth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petrosalema.com" # the base hostname & protocol for your site
twitter_username: petrosalema
github_username:  petrosalema

# Build settings
markdown: kramdown
