title: Petro Salema - React Native & Angular JavaScript expert

description: > # this means to ignore newlines until "baseurl:"
  Petro Salema. React Native/Angular Javascript and mobile expert. Helping companies go from vision to version 1.0

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://petrosalema.com" # the base hostname & protocol for your site

exclude:
    - git
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - README.md

markdown: kramdown


# My book shelf
# Murphy Brown
# The Cry of The Soul
# Counterfeit Gods
# Book me to speak at your conference
# For people who want to make a difference
# step through still as you hover or draf over image
#
# My is Petro, and I work with people who want to make a difference.
# My mission is to...
#
# http://www.elliotmidson.com/
# http://www.clementbrichon.com/work/takeit-website/
# http://diegoaguilar.com/
# http://henrikandsofia.com/
#
#
# https://jekyllrb.com/docs/variables/
# https://jekyllrb.com/docs/frontmatter/
# https://jekyllrb.com/docs/structure/
# https://github.com/nielsenramon/nielsenramon.com
# http://www.anatoliygromov.com/
#
#Over the past 2 years, I've worked as the Head of Online Media Management at
#LOOP in Berlin where I was responsible for all online marketing activities. My
#passion for semantics, analytical correlations and psychological user patterns
#led me to dig deeper into the field of User Experience. I am currently seeking
#out new challenges as a product manager, where I can combine my digital
#marketing background with my knowledge of UX research and strategy.
#
# Creative Direction
# 
# width 0.5s cubic-bezier(1.000, 0.000, 0.000, 1.000) --> http://kasperlaigaard.com/
#
# http://www.taylorevans.co/ -> image zoooming
#
#
